version: "3"
services:
  nginx:
    build: ./web
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./web/web.env
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/nginx.conf:/etc/nginx/nginx.conf.d
      - ./www:/var/www
      - ./web/.htpasswd:/etc/nginx/.htpasswd;
    links:
      - php

  php:
    container_name: php
    build: ./app
    env_file:
      - ./web/web.env
    volumes:
      - ./www:/var/www
      - ./app/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql