version: "3"
services:
  fluentd:
    build: ./fluentd
    ports:
      - 24224:24224
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/log:/var/log/rails
    environment:
      FLUENTD_CONF: fluentd.conf